parameters:
  jobTemplate: ''
  buildConfig: ''
  jobParameters: {}

jobs:

# WebAssembly

- ${{ if ne(parameters.jobParameters.testScenarios, 'CoreFX') }}: # Don't want the second job as it would be a duplicate.
  - template: ${{ parameters.jobTemplate }}
    parameters:
      buildConfig: ${{ parameters.buildConfig }}
      archType: wasm
      osGroup: WebAssembly
      osIdentifier: WebAssembly
      ${{ each param in parameters.jobParameters }}:
        ${{ if ne(param.key, 'testScenarios') }}: # Insert all properties other than "testScenarios"
          ${{ param.key }}: ${{ param.value }}
