parameters:
  jobTemplate: ''
  buildConfig: ''
  jobParameters: {}

jobs:

  # Windows x64

- template: ${{ parameters.jobTemplate }}
  parameters:
    buildConfig: ${{ parameters.buildConfig }}
    archType: x64
    osGroup: Windows_NT
    osIdentifier: Windows_NT
    ${{ insert }}: ${{ parameters.jobParameters }}
