SET( HAVE_CLOCK_MONOTONIC_EXITCODE
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_SCHED_GETCPU_EXITCODE
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_CLOCK_MONOTONIC_COARSE_EXITCODE
     0
     CACHE STRING "Result from TRY_RUN" FORCE)
