// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;

/// <summary>
/// This is used to mark our Interop APIs as generated by MCG so that MCG can skip them
/// Ideally we should be able to ignore them when they are blittable but we still would emit the structs &
/// enums today and I'd like to avoid that.
/// </summary>
[System.AttributeUsageAttribute(System.AttributeTargets.Method)]
internal class McgGeneratedNativeCallCodeAttribute : System.Attribute
{
}
