// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// DO NOT EDIT THIS FILE! It IS AUTOGENERATED
using System;
using System.Runtime.InteropServices;

namespace Internal.JitInterface
{
    unsafe partial class CorInfoImpl
    {
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getMethodAttribs(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _setMethodAttribs(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn, CorInfoMethodRuntimeFlags attribs);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getMethodSig(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn, CORINFO_SIG_INFO* sig, CORINFO_CLASS_STRUCT_* memberParent);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.I1)]delegate bool _getMethodInfo(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn, ref CORINFO_METHOD_INFO info);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoInline _canInline(IntPtr _this, CORINFO_METHOD_STRUCT_* callerHnd, CORINFO_METHOD_STRUCT_* calleeHnd, ref uint pRestrictions);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _reportInliningDecision(IntPtr _this, CORINFO_METHOD_STRUCT_* inlinerHnd, CORINFO_METHOD_STRUCT_* inlineeHnd, CorInfoInline inlineResult, byte* reason);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.I1)]delegate bool _canTailCall(IntPtr _this, CORINFO_METHOD_STRUCT_* callerHnd, CORINFO_METHOD_STRUCT_* declaredCalleeHnd, CORINFO_METHOD_STRUCT_* exactCalleeHnd, [MarshalAs(UnmanagedType.I1)]bool fIsTailPrefix);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _reportTailCallDecision(IntPtr _this, CORINFO_METHOD_STRUCT_* callerHnd, CORINFO_METHOD_STRUCT_* calleeHnd, [MarshalAs(UnmanagedType.I1)]bool fIsTailPrefix, CorInfoTailCall tailCallResult, byte* reason);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getEHinfo(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn, uint EHnumber, ref CORINFO_EH_CLAUSE clause);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_CLASS_STRUCT_* _getMethodClass(IntPtr _this, CORINFO_METHOD_STRUCT_* method);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_MODULE_STRUCT_* _getMethodModule(IntPtr _this, CORINFO_METHOD_STRUCT_* method);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getMethodVTableOffset(IntPtr _this, CORINFO_METHOD_STRUCT_* method, ref uint offsetOfIndirection, ref uint offsetAfterIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoIntrinsics _getIntrinsicID(IntPtr _this, CORINFO_METHOD_STRUCT_* method);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.I1)]delegate bool _isInSIMDModule(IntPtr _this, CORINFO_CLASS_STRUCT_* classHnd);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoUnmanagedCallConv _getUnmanagedCallConv(IntPtr _this, CORINFO_METHOD_STRUCT_* method);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _pInvokeMarshalingRequired(IntPtr _this, CORINFO_METHOD_STRUCT_* method, CORINFO_SIG_INFO* callSiteSig);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _satisfiesMethodConstraints(IntPtr _this, CORINFO_CLASS_STRUCT_* parent, CORINFO_METHOD_STRUCT_* method);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _isCompatibleDelegate(IntPtr _this, CORINFO_CLASS_STRUCT_* objCls, CORINFO_CLASS_STRUCT_* methodParentCls, CORINFO_METHOD_STRUCT_* method, CORINFO_CLASS_STRUCT_* delegateCls, [MarshalAs(UnmanagedType.Bool)] ref bool pfIsOpenDelegate);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _isDelegateCreationAllowed(IntPtr _this, CORINFO_CLASS_STRUCT_* delegateHnd, CORINFO_METHOD_STRUCT_* calleeHnd);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoInstantiationVerification _isInstantiationOfVerifiedGeneric(IntPtr _this, CORINFO_METHOD_STRUCT_* method);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _initConstraintsForVerification(IntPtr _this, CORINFO_METHOD_STRUCT_* method, [MarshalAs(UnmanagedType.Bool)] ref bool pfHasCircularClassConstraints, [MarshalAs(UnmanagedType.Bool)] ref bool pfHasCircularMethodConstraint);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoCanSkipVerificationResult _canSkipMethodVerification(IntPtr _this, CORINFO_METHOD_STRUCT_* ftnHandle);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _methodMustBeLoadedBeforeCodeIsRun(IntPtr _this, CORINFO_METHOD_STRUCT_* method);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_METHOD_STRUCT_* _mapMethodDeclToMethodImpl(IntPtr _this, CORINFO_METHOD_STRUCT_* method);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getGSCookie(IntPtr _this, GSCookie* pCookieVal, GSCookie** ppCookieVal);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _resolveToken(IntPtr _this, ref CORINFO_RESOLVED_TOKEN pResolvedToken);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _findSig(IntPtr _this, CORINFO_MODULE_STRUCT_* module, uint sigTOK, CORINFO_CONTEXT_STRUCT* context, CORINFO_SIG_INFO* sig);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _findCallSiteSig(IntPtr _this, CORINFO_MODULE_STRUCT_* module, uint methTOK, CORINFO_CONTEXT_STRUCT* context, CORINFO_SIG_INFO* sig);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_CLASS_STRUCT_* _getTokenTypeAsHandle(IntPtr _this, ref CORINFO_RESOLVED_TOKEN pResolvedToken);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoCanSkipVerificationResult _canSkipVerification(IntPtr _this, CORINFO_MODULE_STRUCT_* module);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _isValidToken(IntPtr _this, CORINFO_MODULE_STRUCT_* module, uint metaTOK);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _isValidStringRef(IntPtr _this, CORINFO_MODULE_STRUCT_* module, uint metaTOK);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _shouldEnforceCallvirtRestriction(IntPtr _this, CORINFO_MODULE_STRUCT_* scope);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoType _asCorInfoType(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate byte* _getClassName(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate int _appendClassName(IntPtr _this, short** ppBuf, ref int pnBufLen, CORINFO_CLASS_STRUCT_* cls, [MarshalAs(UnmanagedType.Bool)]bool fNamespace, [MarshalAs(UnmanagedType.Bool)]bool fFullInst, [MarshalAs(UnmanagedType.Bool)]bool fAssembly);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _isValueClass(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _canInlineTypeCheckWithObjectVTable(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getClassAttribs(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _isStructRequiringStackAllocRetBuf(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_MODULE_STRUCT_* _getClassModule(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_ASSEMBLY_STRUCT_* _getModuleAssembly(IntPtr _this, CORINFO_MODULE_STRUCT_* mod);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate byte* _getAssemblyName(IntPtr _this, CORINFO_ASSEMBLY_STRUCT_* assem);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _LongLifetimeMalloc(IntPtr _this, UIntPtr sz);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _LongLifetimeFree(IntPtr _this, void* obj);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate byte* _getClassModuleIdForStatics(IntPtr _this, CORINFO_CLASS_STRUCT_* cls, CORINFO_MODULE_STRUCT_** pModule, void** ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getClassSize(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getClassAlignmentRequirement(IntPtr _this, CORINFO_CLASS_STRUCT_* cls, [MarshalAs(UnmanagedType.Bool)]bool fDoubleAlignHint);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getClassGClayout(IntPtr _this, CORINFO_CLASS_STRUCT_* cls, byte* gcPtrs);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getClassNumInstanceFields(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_FIELD_STRUCT_* _getFieldInClass(IntPtr _this, CORINFO_CLASS_STRUCT_* clsHnd, int num);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _checkMethodModifier(IntPtr _this, CORINFO_METHOD_STRUCT_* hMethod, byte* modifier, [MarshalAs(UnmanagedType.Bool)]bool fOptional);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoHelpFunc _getNewHelper(IntPtr _this, ref CORINFO_RESOLVED_TOKEN pResolvedToken, CORINFO_METHOD_STRUCT_* callerHandle);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoHelpFunc _getNewArrHelper(IntPtr _this, CORINFO_CLASS_STRUCT_* arrayCls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoHelpFunc _getCastingHelper(IntPtr _this, ref CORINFO_RESOLVED_TOKEN pResolvedToken, [MarshalAs(UnmanagedType.I1)]bool fThrowing);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoHelpFunc _getSharedCCtorHelper(IntPtr _this, CORINFO_CLASS_STRUCT_* clsHnd);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoHelpFunc _getSecurityPrologHelper(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_CLASS_STRUCT_* _getTypeForBox(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoHelpFunc _getBoxHelper(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoHelpFunc _getUnBoxHelper(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getReadyToRunHelper(IntPtr _this, ref CORINFO_RESOLVED_TOKEN pResolvedToken, CorInfoHelpFunc id, ref CORINFO_CONST_LOOKUP pLookup);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate byte* _getHelperName(IntPtr _this, CorInfoHelpFunc helpFunc);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoInitClassResult _initClass(IntPtr _this, CORINFO_FIELD_STRUCT_* field, CORINFO_METHOD_STRUCT_* method, CORINFO_CONTEXT_STRUCT* context, [MarshalAs(UnmanagedType.Bool)]bool speculative);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _classMustBeLoadedBeforeCodeIsRun(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_CLASS_STRUCT_* _getBuiltinClass(IntPtr _this, CorInfoClassId classId);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoType _getTypeForPrimitiveValueClass(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _canCast(IntPtr _this, CORINFO_CLASS_STRUCT_* child, CORINFO_CLASS_STRUCT_* parent);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _areTypesEquivalent(IntPtr _this, CORINFO_CLASS_STRUCT_* cls1, CORINFO_CLASS_STRUCT_* cls2);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_CLASS_STRUCT_* _mergeClasses(IntPtr _this, CORINFO_CLASS_STRUCT_* cls1, CORINFO_CLASS_STRUCT_* cls2);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_CLASS_STRUCT_* _getParentType(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoType _getChildType(IntPtr _this, CORINFO_CLASS_STRUCT_* clsHnd, ref CORINFO_CLASS_STRUCT_* clsRet);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _satisfiesClassConstraints(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _isSDArray(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getArrayRank(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _getArrayInitializationData(IntPtr _this, CORINFO_FIELD_STRUCT_* field, uint size);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoIsAccessAllowedResult _canAccessClass(IntPtr _this, ref CORINFO_RESOLVED_TOKEN pResolvedToken, CORINFO_METHOD_STRUCT_* callerHandle, ref CORINFO_HELPER_DESC pAccessHelper);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate byte* _getFieldName(IntPtr _this, CORINFO_FIELD_STRUCT_* ftn, byte** moduleName);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_CLASS_STRUCT_* _getFieldClass(IntPtr _this, CORINFO_FIELD_STRUCT_* field);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoType _getFieldType(IntPtr _this, CORINFO_FIELD_STRUCT_* field, ref CORINFO_CLASS_STRUCT_* structType, CORINFO_CLASS_STRUCT_* memberParent);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getFieldOffset(IntPtr _this, CORINFO_FIELD_STRUCT_* field);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.I1)]delegate bool _isWriteBarrierHelperRequired(IntPtr _this, CORINFO_FIELD_STRUCT_* field);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getFieldInfo(IntPtr _this, ref CORINFO_RESOLVED_TOKEN pResolvedToken, CORINFO_METHOD_STRUCT_* callerHandle, CORINFO_ACCESS_FLAGS flags, ref CORINFO_FIELD_INFO pResult);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.I1)]delegate bool _isFieldStatic(IntPtr _this, CORINFO_FIELD_STRUCT_* fldHnd);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getBoundaries(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn, ref uint cILOffsets, ref uint* pILOffsets, BoundaryTypes* implictBoundaries);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _setBoundaries(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn, uint cMap, OffsetMapping* pMap);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getVars(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn, ref uint cVars, ILVarInfo** vars, [MarshalAs(UnmanagedType.U1)] ref bool extendOthers);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _setVars(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn, uint cVars, NativeVarInfo* vars);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _allocateArray(IntPtr _this, uint cBytes);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _freeArray(IntPtr _this, void* array);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_ARG_LIST_STRUCT_* _getArgNext(IntPtr _this, CORINFO_ARG_LIST_STRUCT_* args);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoTypeWithMod _getArgType(IntPtr _this, CORINFO_SIG_INFO* sig, CORINFO_ARG_LIST_STRUCT_* args, ref CORINFO_CLASS_STRUCT_* vcTypeRet);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_CLASS_STRUCT_* _getArgClass(IntPtr _this, CORINFO_SIG_INFO* sig, CORINFO_ARG_LIST_STRUCT_* args);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoType _getHFAType(IntPtr _this, CORINFO_CLASS_STRUCT_* hClass);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate HRESULT _GetErrorHRESULT(IntPtr _this, _EXCEPTION_POINTERS* pExceptionPointers);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _GetErrorMessage(IntPtr _this, short* buffer, uint bufferLength);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate int _FilterException(IntPtr _this, _EXCEPTION_POINTERS* pExceptionPointers);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _HandleException(IntPtr _this, _EXCEPTION_POINTERS* pExceptionPointers);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _ThrowExceptionForJitResult(IntPtr _this, HRESULT result);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _ThrowExceptionForHelper(IntPtr _this, ref CORINFO_HELPER_DESC throwHelper);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getEEInfo(IntPtr _this, ref CORINFO_EE_INFO pEEInfoOut);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.LPWStr)]delegate string _getJitTimeLogFilename(IntPtr _this);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate mdToken _getMethodDefFromMethod(IntPtr _this, CORINFO_METHOD_STRUCT_* hMethod);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate byte* _getMethodName(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn, byte** moduleName);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getMethodHash(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate byte* _findNameOfToken(IntPtr _this, CORINFO_MODULE_STRUCT_* moduleHandle, mdToken token, byte* szFQName, UIntPtr FQNameCapacity);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate int _getIntConfigValue(IntPtr _this, String name, int defaultValue);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate short* _getStringConfigValue(IntPtr _this, String name);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _freeStringConfigValue(IntPtr _this, short* value);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getThreadTLSIndex(IntPtr _this, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _getInlinedCallFrameVptr(IntPtr _this, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate int* _getAddrOfCaptureThreadGlobal(IntPtr _this, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate SIZE_T* _getAddrModuleDomainID(IntPtr _this, CORINFO_MODULE_STRUCT_* module);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _getHelperFtn(IntPtr _this, CorInfoHelpFunc ftnNum, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getFunctionEntryPoint(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn, ref CORINFO_CONST_LOOKUP pResult, CORINFO_ACCESS_FLAGS accessFlags);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getFunctionFixedEntryPoint(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn, ref CORINFO_CONST_LOOKUP pResult);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _getMethodSync(IntPtr _this, CORINFO_METHOD_STRUCT_* ftn, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CorInfoHelpFunc _getLazyStringLiteralHelper(IntPtr _this, CORINFO_MODULE_STRUCT_* handle);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_MODULE_STRUCT_* _embedModuleHandle(IntPtr _this, CORINFO_MODULE_STRUCT_* handle, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_CLASS_STRUCT_* _embedClassHandle(IntPtr _this, CORINFO_CLASS_STRUCT_* handle, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_METHOD_STRUCT_* _embedMethodHandle(IntPtr _this, CORINFO_METHOD_STRUCT_* handle, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_FIELD_STRUCT_* _embedFieldHandle(IntPtr _this, CORINFO_FIELD_STRUCT_* handle, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _embedGenericHandle(IntPtr _this, ref CORINFO_RESOLVED_TOKEN pResolvedToken, [MarshalAs(UnmanagedType.Bool)]bool fEmbedParent, ref CORINFO_GENERICHANDLE_RESULT pResult);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_LOOKUP_KIND _getLocationOfThisType(IntPtr _this, CORINFO_METHOD_STRUCT_* context);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _getPInvokeUnmanagedTarget(IntPtr _this, CORINFO_METHOD_STRUCT_* method, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _getAddressOfPInvokeFixup(IntPtr _this, CORINFO_METHOD_STRUCT_* method, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _GetCookieForPInvokeCalliSig(IntPtr _this, CORINFO_SIG_INFO* szMetaSig, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.I1)]delegate bool _canGetCookieForPInvokeCalliSig(IntPtr _this, CORINFO_SIG_INFO* szMetaSig);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_JUST_MY_CODE_HANDLE_* _getJustMyCodeHandle(IntPtr _this, CORINFO_METHOD_STRUCT_* method, ref CORINFO_JUST_MY_CODE_HANDLE_** ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _GetProfilingHandle(IntPtr _this, [MarshalAs(UnmanagedType.Bool)] ref bool pbHookFunction, ref void* pProfilerHandle, [MarshalAs(UnmanagedType.Bool)] ref bool pbIndirectedHandles);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getCallInfo(IntPtr _this, ref CORINFO_RESOLVED_TOKEN pResolvedToken, CORINFO_RESOLVED_TOKEN* pConstrainedResolvedToken, CORINFO_METHOD_STRUCT_* callerHandle, CORINFO_CALLINFO_FLAGS flags, ref CORINFO_CALL_INFO pResult);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _canAccessFamily(IntPtr _this, CORINFO_METHOD_STRUCT_* hCaller, CORINFO_CLASS_STRUCT_* hInstanceType);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _isRIDClassDomainID(IntPtr _this, CORINFO_CLASS_STRUCT_* cls);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getClassDomainID(IntPtr _this, CORINFO_CLASS_STRUCT_* cls, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _getFieldAddress(IntPtr _this, CORINFO_FIELD_STRUCT_* field, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate IntPtr _getVarArgsHandle(IntPtr _this, CORINFO_SIG_INFO* pSig, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.I1)]delegate bool _canGetVarArgsHandle(IntPtr _this, CORINFO_SIG_INFO* pSig);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate InfoAccessType _constructStringLiteral(IntPtr _this, CORINFO_MODULE_STRUCT_* module, mdToken metaTok, ref void* ppValue);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate InfoAccessType _emptyStringLiteral(IntPtr _this, ref void* ppValue);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getFieldThreadLocalStoreID(IntPtr _this, CORINFO_FIELD_STRUCT_* field, ref void* ppIndirection);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _setOverride(IntPtr _this, IntPtr pOverride, CORINFO_METHOD_STRUCT_* currentMethod);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _addActiveDependency(IntPtr _this, CORINFO_MODULE_STRUCT_* moduleFrom, CORINFO_MODULE_STRUCT_* moduleTo);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate CORINFO_METHOD_STRUCT_* _GetDelegateCtor(IntPtr _this, CORINFO_METHOD_STRUCT_* methHnd, CORINFO_CLASS_STRUCT_* clsHnd, CORINFO_METHOD_STRUCT_* targetMethodHnd, ref DelegateCtorArgs pCtorData);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _MethodCompileComplete(IntPtr _this, CORINFO_METHOD_STRUCT_* methHnd);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _getTailCallCopyArgsThunk(IntPtr _this, CORINFO_SIG_INFO* pSig, CorInfoHelperTailCallSpecialHandling flags);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _getMemoryManager(IntPtr _this);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _allocMem(IntPtr _this, uint hotCodeSize, uint coldCodeSize, uint roDataSize, uint xcptnsCount, CorJitAllocMemFlag flag, ref void* hotCodeBlock, ref void* coldCodeBlock, ref void* roDataBlock);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _reserveUnwindInfo(IntPtr _this, [MarshalAs(UnmanagedType.Bool)]bool isFunclet, [MarshalAs(UnmanagedType.Bool)]bool isColdCode, uint unwindSize);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _allocUnwindInfo(IntPtr _this, byte* pHotCode, byte* pColdCode, uint startOffset, uint endOffset, uint unwindSize, byte* pUnwindBlock, CorJitFuncKind funcKind);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void* _allocGCInfo(IntPtr _this, UIntPtr size);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _yieldExecution(IntPtr _this);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _setEHcount(IntPtr _this, uint cEH);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _setEHinfo(IntPtr _this, uint EHnumber, ref CORINFO_EH_CLAUSE clause);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        [return: MarshalAs(UnmanagedType.Bool)]delegate bool _logMsg(IntPtr _this, uint level, byte* fmt, IntPtr args);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate int _doAssert(IntPtr _this, byte* szFile, int iLine, byte* szExpr);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _reportFatalError(IntPtr _this, CorJitResult result);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate HRESULT _allocBBProfileBuffer(IntPtr _this, uint count, ref ProfileBuffer* profileBuffer);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate HRESULT _getBBProfileData(IntPtr _this, CORINFO_METHOD_STRUCT_* ftnHnd, ref uint count, ref ProfileBuffer* profileBuffer, ref uint numRuns);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _recordCallSite(IntPtr _this, uint instrOffset, CORINFO_SIG_INFO* callSig, CORINFO_METHOD_STRUCT_* methodHandle);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _recordRelocation(IntPtr _this, void* location, void* target, ushort fRelocType, ushort slotNum, int addlDelta);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate ushort _getRelocTypeHint(IntPtr _this, void* target);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate void _getModuleNativeEntryPointRange(IntPtr _this, ref void* pStart, ref void* pEnd);
        [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
        delegate uint _getExpectedTargetArchitecture(IntPtr _this);

        Object[] _keepalive;

        protected IntPtr CreateUnmanagedInstance()
        {
            IntPtr * vtable = (IntPtr *)Marshal.AllocCoTaskMem(sizeof(IntPtr) * 162);
            Object[] keepalive = new Object[162];
            Delegate d;

            _keepalive = keepalive;

            d = new _getMethodAttribs(getMethodAttribs);
            vtable[0] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[0] = d;
            d = new _setMethodAttribs(setMethodAttribs);
            vtable[1] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[1] = d;
            d = new _getMethodSig(getMethodSig);
            vtable[2] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[2] = d;
            d = new _getMethodInfo(getMethodInfo);
            vtable[3] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[3] = d;
            d = new _canInline(canInline);
            vtable[4] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[4] = d;
            d = new _reportInliningDecision(reportInliningDecision);
            vtable[5] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[5] = d;
            d = new _canTailCall(canTailCall);
            vtable[6] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[6] = d;
            d = new _reportTailCallDecision(reportTailCallDecision);
            vtable[7] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[7] = d;
            d = new _getEHinfo(getEHinfo);
            vtable[8] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[8] = d;
            d = new _getMethodClass(getMethodClass);
            vtable[9] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[9] = d;
            d = new _getMethodModule(getMethodModule);
            vtable[10] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[10] = d;
            d = new _getMethodVTableOffset(getMethodVTableOffset);
            vtable[11] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[11] = d;
            d = new _getIntrinsicID(getIntrinsicID);
            vtable[12] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[12] = d;
            d = new _isInSIMDModule(isInSIMDModule);
            vtable[13] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[13] = d;
            d = new _getUnmanagedCallConv(getUnmanagedCallConv);
            vtable[14] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[14] = d;
            d = new _pInvokeMarshalingRequired(pInvokeMarshalingRequired);
            vtable[15] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[15] = d;
            d = new _satisfiesMethodConstraints(satisfiesMethodConstraints);
            vtable[16] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[16] = d;
            d = new _isCompatibleDelegate(isCompatibleDelegate);
            vtable[17] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[17] = d;
            d = new _isDelegateCreationAllowed(isDelegateCreationAllowed);
            vtable[18] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[18] = d;
            d = new _isInstantiationOfVerifiedGeneric(isInstantiationOfVerifiedGeneric);
            vtable[19] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[19] = d;
            d = new _initConstraintsForVerification(initConstraintsForVerification);
            vtable[20] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[20] = d;
            d = new _canSkipMethodVerification(canSkipMethodVerification);
            vtable[21] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[21] = d;
            d = new _methodMustBeLoadedBeforeCodeIsRun(methodMustBeLoadedBeforeCodeIsRun);
            vtable[22] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[22] = d;
            d = new _mapMethodDeclToMethodImpl(mapMethodDeclToMethodImpl);
            vtable[23] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[23] = d;
            d = new _getGSCookie(getGSCookie);
            vtable[24] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[24] = d;
            d = new _resolveToken(resolveToken);
            vtable[25] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[25] = d;
            d = new _findSig(findSig);
            vtable[26] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[26] = d;
            d = new _findCallSiteSig(findCallSiteSig);
            vtable[27] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[27] = d;
            d = new _getTokenTypeAsHandle(getTokenTypeAsHandle);
            vtable[28] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[28] = d;
            d = new _canSkipVerification(canSkipVerification);
            vtable[29] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[29] = d;
            d = new _isValidToken(isValidToken);
            vtable[30] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[30] = d;
            d = new _isValidStringRef(isValidStringRef);
            vtable[31] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[31] = d;
            d = new _shouldEnforceCallvirtRestriction(shouldEnforceCallvirtRestriction);
            vtable[32] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[32] = d;
            d = new _asCorInfoType(asCorInfoType);
            vtable[33] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[33] = d;
            d = new _getClassName(getClassName);
            vtable[34] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[34] = d;
            d = new _appendClassName(appendClassName);
            vtable[35] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[35] = d;
            d = new _isValueClass(isValueClass);
            vtable[36] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[36] = d;
            d = new _canInlineTypeCheckWithObjectVTable(canInlineTypeCheckWithObjectVTable);
            vtable[37] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[37] = d;
            d = new _getClassAttribs(getClassAttribs);
            vtable[38] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[38] = d;
            d = new _isStructRequiringStackAllocRetBuf(isStructRequiringStackAllocRetBuf);
            vtable[39] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[39] = d;
            d = new _getClassModule(getClassModule);
            vtable[40] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[40] = d;
            d = new _getModuleAssembly(getModuleAssembly);
            vtable[41] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[41] = d;
            d = new _getAssemblyName(getAssemblyName);
            vtable[42] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[42] = d;
            d = new _LongLifetimeMalloc(LongLifetimeMalloc);
            vtable[43] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[43] = d;
            d = new _LongLifetimeFree(LongLifetimeFree);
            vtable[44] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[44] = d;
            d = new _getClassModuleIdForStatics(getClassModuleIdForStatics);
            vtable[45] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[45] = d;
            d = new _getClassSize(getClassSize);
            vtable[46] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[46] = d;
            d = new _getClassAlignmentRequirement(getClassAlignmentRequirement);
            vtable[47] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[47] = d;
            d = new _getClassGClayout(getClassGClayout);
            vtable[48] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[48] = d;
            d = new _getClassNumInstanceFields(getClassNumInstanceFields);
            vtable[49] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[49] = d;
            d = new _getFieldInClass(getFieldInClass);
            vtable[50] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[50] = d;
            d = new _checkMethodModifier(checkMethodModifier);
            vtable[51] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[51] = d;
            d = new _getNewHelper(getNewHelper);
            vtable[52] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[52] = d;
            d = new _getNewArrHelper(getNewArrHelper);
            vtable[53] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[53] = d;
            d = new _getCastingHelper(getCastingHelper);
            vtable[54] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[54] = d;
            d = new _getSharedCCtorHelper(getSharedCCtorHelper);
            vtable[55] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[55] = d;
            d = new _getSecurityPrologHelper(getSecurityPrologHelper);
            vtable[56] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[56] = d;
            d = new _getTypeForBox(getTypeForBox);
            vtable[57] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[57] = d;
            d = new _getBoxHelper(getBoxHelper);
            vtable[58] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[58] = d;
            d = new _getUnBoxHelper(getUnBoxHelper);
            vtable[59] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[59] = d;
            d = new _getReadyToRunHelper(getReadyToRunHelper);
            vtable[60] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[60] = d;
            d = new _getHelperName(getHelperName);
            vtable[61] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[61] = d;
            d = new _initClass(initClass);
            vtable[62] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[62] = d;
            d = new _classMustBeLoadedBeforeCodeIsRun(classMustBeLoadedBeforeCodeIsRun);
            vtable[63] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[63] = d;
            d = new _getBuiltinClass(getBuiltinClass);
            vtable[64] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[64] = d;
            d = new _getTypeForPrimitiveValueClass(getTypeForPrimitiveValueClass);
            vtable[65] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[65] = d;
            d = new _canCast(canCast);
            vtable[66] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[66] = d;
            d = new _areTypesEquivalent(areTypesEquivalent);
            vtable[67] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[67] = d;
            d = new _mergeClasses(mergeClasses);
            vtable[68] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[68] = d;
            d = new _getParentType(getParentType);
            vtable[69] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[69] = d;
            d = new _getChildType(getChildType);
            vtable[70] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[70] = d;
            d = new _satisfiesClassConstraints(satisfiesClassConstraints);
            vtable[71] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[71] = d;
            d = new _isSDArray(isSDArray);
            vtable[72] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[72] = d;
            d = new _getArrayRank(getArrayRank);
            vtable[73] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[73] = d;
            d = new _getArrayInitializationData(getArrayInitializationData);
            vtable[74] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[74] = d;
            d = new _canAccessClass(canAccessClass);
            vtable[75] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[75] = d;
            d = new _getFieldName(getFieldName);
            vtable[76] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[76] = d;
            d = new _getFieldClass(getFieldClass);
            vtable[77] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[77] = d;
            d = new _getFieldType(getFieldType);
            vtable[78] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[78] = d;
            d = new _getFieldOffset(getFieldOffset);
            vtable[79] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[79] = d;
            d = new _isWriteBarrierHelperRequired(isWriteBarrierHelperRequired);
            vtable[80] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[80] = d;
            d = new _getFieldInfo(getFieldInfo);
            vtable[81] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[81] = d;
            d = new _isFieldStatic(isFieldStatic);
            vtable[82] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[82] = d;
            d = new _getBoundaries(getBoundaries);
            vtable[83] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[83] = d;
            d = new _setBoundaries(setBoundaries);
            vtable[84] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[84] = d;
            d = new _getVars(getVars);
            vtable[85] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[85] = d;
            d = new _setVars(setVars);
            vtable[86] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[86] = d;
            d = new _allocateArray(allocateArray);
            vtable[87] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[87] = d;
            d = new _freeArray(freeArray);
            vtable[88] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[88] = d;
            d = new _getArgNext(getArgNext);
            vtable[89] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[89] = d;
            d = new _getArgType(getArgType);
            vtable[90] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[90] = d;
            d = new _getArgClass(getArgClass);
            vtable[91] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[91] = d;
            d = new _getHFAType(getHFAType);
            vtable[92] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[92] = d;
            d = new _GetErrorHRESULT(GetErrorHRESULT);
            vtable[93] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[93] = d;
            d = new _GetErrorMessage(GetErrorMessage);
            vtable[94] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[94] = d;
            d = new _FilterException(FilterException);
            vtable[95] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[95] = d;
            d = new _HandleException(HandleException);
            vtable[96] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[96] = d;
            d = new _ThrowExceptionForJitResult(ThrowExceptionForJitResult);
            vtable[97] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[97] = d;
            d = new _ThrowExceptionForHelper(ThrowExceptionForHelper);
            vtable[98] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[98] = d;
            d = new _getEEInfo(getEEInfo);
            vtable[99] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[99] = d;
            d = new _getJitTimeLogFilename(getJitTimeLogFilename);
            vtable[100] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[100] = d;
            d = new _getMethodDefFromMethod(getMethodDefFromMethod);
            vtable[101] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[101] = d;
            d = new _getMethodName(getMethodName);
            vtable[102] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[102] = d;
            d = new _getMethodHash(getMethodHash);
            vtable[103] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[103] = d;
            d = new _findNameOfToken(findNameOfToken);
            vtable[104] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[104] = d;
            d = new _getIntConfigValue(getIntConfigValue);
            vtable[105] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[105] = d;
            d = new _getStringConfigValue(getStringConfigValue);
            vtable[106] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[106] = d;
            d = new _freeStringConfigValue(freeStringConfigValue);
            vtable[107] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[107] = d;
            d = new _getThreadTLSIndex(getThreadTLSIndex);
            vtable[108] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[108] = d;
            d = new _getInlinedCallFrameVptr(getInlinedCallFrameVptr);
            vtable[109] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[109] = d;
            d = new _getAddrOfCaptureThreadGlobal(getAddrOfCaptureThreadGlobal);
            vtable[110] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[110] = d;
            d = new _getAddrModuleDomainID(getAddrModuleDomainID);
            vtable[111] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[111] = d;
            d = new _getHelperFtn(getHelperFtn);
            vtable[112] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[112] = d;
            d = new _getFunctionEntryPoint(getFunctionEntryPoint);
            vtable[113] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[113] = d;
            d = new _getFunctionFixedEntryPoint(getFunctionFixedEntryPoint);
            vtable[114] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[114] = d;
            d = new _getMethodSync(getMethodSync);
            vtable[115] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[115] = d;
            d = new _getLazyStringLiteralHelper(getLazyStringLiteralHelper);
            vtable[116] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[116] = d;
            d = new _embedModuleHandle(embedModuleHandle);
            vtable[117] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[117] = d;
            d = new _embedClassHandle(embedClassHandle);
            vtable[118] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[118] = d;
            d = new _embedMethodHandle(embedMethodHandle);
            vtable[119] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[119] = d;
            d = new _embedFieldHandle(embedFieldHandle);
            vtable[120] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[120] = d;
            d = new _embedGenericHandle(embedGenericHandle);
            vtable[121] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[121] = d;
            d = new _getLocationOfThisType(getLocationOfThisType);
            vtable[122] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[122] = d;
            d = new _getPInvokeUnmanagedTarget(getPInvokeUnmanagedTarget);
            vtable[123] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[123] = d;
            d = new _getAddressOfPInvokeFixup(getAddressOfPInvokeFixup);
            vtable[124] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[124] = d;
            d = new _GetCookieForPInvokeCalliSig(GetCookieForPInvokeCalliSig);
            vtable[125] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[125] = d;
            d = new _canGetCookieForPInvokeCalliSig(canGetCookieForPInvokeCalliSig);
            vtable[126] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[126] = d;
            d = new _getJustMyCodeHandle(getJustMyCodeHandle);
            vtable[127] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[127] = d;
            d = new _GetProfilingHandle(GetProfilingHandle);
            vtable[128] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[128] = d;
            d = new _getCallInfo(getCallInfo);
            vtable[129] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[129] = d;
            d = new _canAccessFamily(canAccessFamily);
            vtable[130] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[130] = d;
            d = new _isRIDClassDomainID(isRIDClassDomainID);
            vtable[131] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[131] = d;
            d = new _getClassDomainID(getClassDomainID);
            vtable[132] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[132] = d;
            d = new _getFieldAddress(getFieldAddress);
            vtable[133] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[133] = d;
            d = new _getVarArgsHandle(getVarArgsHandle);
            vtable[134] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[134] = d;
            d = new _canGetVarArgsHandle(canGetVarArgsHandle);
            vtable[135] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[135] = d;
            d = new _constructStringLiteral(constructStringLiteral);
            vtable[136] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[136] = d;
            d = new _emptyStringLiteral(emptyStringLiteral);
            vtable[137] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[137] = d;
            d = new _getFieldThreadLocalStoreID(getFieldThreadLocalStoreID);
            vtable[138] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[138] = d;
            d = new _setOverride(setOverride);
            vtable[139] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[139] = d;
            d = new _addActiveDependency(addActiveDependency);
            vtable[140] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[140] = d;
            d = new _GetDelegateCtor(GetDelegateCtor);
            vtable[141] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[141] = d;
            d = new _MethodCompileComplete(MethodCompileComplete);
            vtable[142] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[142] = d;
            d = new _getTailCallCopyArgsThunk(getTailCallCopyArgsThunk);
            vtable[143] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[143] = d;
            d = new _getMemoryManager(getMemoryManager);
            vtable[144] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[144] = d;
            d = new _allocMem(allocMem);
            vtable[145] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[145] = d;
            d = new _reserveUnwindInfo(reserveUnwindInfo);
            vtable[146] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[146] = d;
            d = new _allocUnwindInfo(allocUnwindInfo);
            vtable[147] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[147] = d;
            d = new _allocGCInfo(allocGCInfo);
            vtable[148] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[148] = d;
            d = new _yieldExecution(yieldExecution);
            vtable[149] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[149] = d;
            d = new _setEHcount(setEHcount);
            vtable[150] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[150] = d;
            d = new _setEHinfo(setEHinfo);
            vtable[151] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[151] = d;
            d = new _logMsg(logMsg);
            vtable[152] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[152] = d;
            d = new _doAssert(doAssert);
            vtable[153] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[153] = d;
            d = new _reportFatalError(reportFatalError);
            vtable[154] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[154] = d;
            d = new _allocBBProfileBuffer(allocBBProfileBuffer);
            vtable[155] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[155] = d;
            d = new _getBBProfileData(getBBProfileData);
            vtable[156] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[156] = d;
            d = new _recordCallSite(recordCallSite);
            vtable[157] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[157] = d;
            d = new _recordRelocation(recordRelocation);
            vtable[158] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[158] = d;
            d = new _getRelocTypeHint(getRelocTypeHint);
            vtable[159] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[159] = d;
            d = new _getModuleNativeEntryPointRange(getModuleNativeEntryPointRange);
            vtable[160] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[160] = d;
            d = new _getExpectedTargetArchitecture(getExpectedTargetArchitecture);
            vtable[161] = Marshal.GetFunctionPointerForDelegate(d);
            keepalive[161] = d;

            IntPtr instance = Marshal.AllocCoTaskMem(sizeof(IntPtr));
            *(IntPtr**)instance = vtable;
            return instance;
        }
    }
}

