// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// TODO: Implement these. See InteropThunksHelpers.s under other architectures for how
// each function should work. This file should ideally be pure WebAssembly for better speed.

#include <AsmOffsets.inc>         // generated by the build from AsmOffsets.cpp
#include <cassert>

#define POINTER_SIZE 4

//
// RhCommonStub
//
// Custom calling convention
typedef void (*RhCommonStub_t)();
extern "C" void RhCommonStub()
{
    assert(false);
}

//
// IntPtr RhGetCommonStubAddress()
//
extern "C" RhCommonStub_t RhGetCommonStubAddress()
{
    return RhCommonStub;
}

//
// IntPtr RhGetCurrentThunkContext()
//
extern "C" void* RhGetCurrentThunkContext()
{
    assert(false);
}
