// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.AmbiguousMatchException))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.Assembly))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.AssemblyContentType))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.AssemblyName))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.BindingFlags))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.ConstructorInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.CustomAttributeData))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.CustomAttributeNamedArgument))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.CustomAttributeTypedArgument))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.EventInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.FieldInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.ICustomAttributeProvider))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.IntrospectionExtensions))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.InvalidFilterCriteriaException))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.IReflectableType))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.LocalVariableInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.ManifestResourceInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.MemberFilter))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.MemberInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.MemberTypes))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.MethodBase))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.MethodInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.Module))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.ParameterInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.ParameterModifier))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.PropertyInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.ReflectionContext))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.ReflectionTypeLoadException))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.ResourceLocation))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.TargetException))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.TypeFilter))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reflection.TypeInfo))]

[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(Internal.Reflection.Extensibility.ExtensibleAssembly))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(Internal.Reflection.Extensibility.ExtensibleConstructorInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(Internal.Reflection.Extensibility.ExtensibleCustomAttributeData))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(Internal.Reflection.Extensibility.ExtensibleEventInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(Internal.Reflection.Extensibility.ExtensibleFieldInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(Internal.Reflection.Extensibility.ExtensibleMethodInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(Internal.Reflection.Extensibility.ExtensibleModule))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(Internal.Reflection.Extensibility.ExtensibleParameterInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(Internal.Reflection.Extensibility.ExtensiblePropertyInfo))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(Internal.Reflection.Extensibility.ExtensibleTypeInfo))]

