// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Runtime.CompilerServices;

namespace System.Runtime
{
    internal static class BinderIntrinsics
    {
#if CORERT
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static void TailCall_RhpThrowEx(Exception e)
        {
            throw e;
        }
#else // CORERT
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.NoOptimization)]
        internal static void TailCall_RhpThrowEx(Exception e)
        {
            // Ignore body of method, it will be generated by the binder.
        }
#endif // CORERT
    }
}
