// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(Internal.Threading.Tasks.AsyncCausalitySupport))]

[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.AggregateException))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.OperationCanceledException))]

[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.AsyncTaskMethodBuilder))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.AsyncTaskMethodBuilder<>))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.AsyncVoidMethodBuilder))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.IAsyncStateMachine))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.ICriticalNotifyCompletion))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.INotifyCompletion))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.ConfiguredTaskAwaitable))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.ConfiguredTaskAwaitable<>))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.TaskAwaiter))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.TaskAwaiter<>))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.YieldAwaitable))]

[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.AsyncLocal<>))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.AsyncLocalValueChangedArgs<>))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.CancellationToken))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.CancellationTokenRegistration))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.CancellationTokenSource))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.ContextCallback))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.ExecutionContext))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.LockRecursionException))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.LockRecursionPolicy))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.ManualResetEventSlim))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.ReaderWriterLockSlim))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.SemaphoreSlim))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.SendOrPostCallback))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.SpinLock))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.SynchronizationContext))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.ThreadLocal<>))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Timer))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.TimerCallback))]

[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.ConcurrentExclusiveSchedulerPair))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.Task))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.Task<>))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.TaskCanceledException))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.TaskCompletionSource<>))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.TaskContinuationOptions))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.TaskCreationOptions))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.TaskFactory))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.TaskFactory<>))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.TaskScheduler))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.TaskSchedulerException))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.TaskStatus))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.Tasks.UnobservedTaskExceptionEventArgs))]